"""Fixing my mistake
Revision ID: 6d19acd4724e
Revises: 5806179c97f8
Create Date: 2021-10-09 16:46:46.265182
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = '6d19acd4724e'
down_revision = '5806179c97f8'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terrorist_act',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('approx_date', sa.String(length=64), nullable=True),
    sa.Column('extended', sa.Boolean(), nullable=False),
    sa.Column('resolution', sa.Date(), nullable=True),
    sa.Column('country', sa.Integer(), nullable=True),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('prov_state', sa.Integer(), nullable=True),
    sa.Column('city', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('specificity', sa.Integer(), nullable=False),
    sa.Column('vicinity', sa.Boolean(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['city'], ['city.id'], ),
    sa.ForeignKeyConstraint(['country'], ['country.id'], ),
    sa.ForeignKeyConstraint(['location'], ['location.id'], ),
    sa.ForeignKeyConstraint(['prov_state'], ['prov_state.id'], ),
    sa.ForeignKeyConstraint(['region'], ['region.id'], ),
    sa.ForeignKeyConstraint(['specificity'], ['specificity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terrorist_act')
    # ### end Alembic commands ###